version: "3"

services:
    app:
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html

    nginx:
        image: nginx:latest
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app